spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/financas
    username: root
    password: 852456
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
